version: "3.7"

services:
    fullstack_challenge_db:
        image: postgres
        container_name: fullstack_challenge_db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fullstack_challenge
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: fullstack_challenge
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - fullstack_challenge_db
        depends_on:
            - fullstack_challenge_db
volumes:
    pgdata:
        driver: local
